import Image from "next/image";

export const metadata = {
	title: "Mobidder",
	description: "Generated by create next app",
};

export default function Home() {
	return <main className=""></main>;
}
